name: Run API Tests
on:
  workflow_dispatch:
  push:
    branches: [test]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build
        run: mvn clean install -DskipTests=true

      - name: Run Tests
        run: mvn test -DsuiteXMLFile=src/test/resources/suites/regression.xml

      - name: Export TestNG Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-tests-report
          path: |
            ./target/surefire-reports
            ./target/allure-results

      - name: Delete Target File After Tests Completed
        if: always()
        run: rm -r ./target